# Your Solution
version: '3'
services:
  book_catalog:
    image: book_catalog:20240916
    # build: 
    #   context: .\book_catalog
    #   dockerfile: Dockerfile
    container_name: book_catalog
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    restart: "no"
  inventory_management:
    image: inventory_management:20240916
    # build: 
    #   context: .\inventory_management
    #   dockerfile: Dockerfile
    container_name: inventory_management
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
    restart: "no"
 


